### ISSUE TITLE
Callback access

### ISSUE THREAD

**Issue by knacky34** [dialogs/android-dialer#1]
Hello, 
I can not implement the DialpadActivity.Callback interface so can not set actions to the call button
I don't know if I done something wrong, I also tried to implement DialpadFragment.Callback but it's in package-private access.

Thanks

**Comment by bmaslakov** [comment]
Hi @knacky34 
Please check `im.dlg:android-dialer:1.2.4`. Sorry for this silly mistake :)

**Comment by knacky34** [comment]
thank you :)

**Comment by knacky34** [comment]
In the README file, usage 1), you should change  DialpadActivity.Callback by DialpadFragment.Callback

**Comment by bmaslakov** [comment]
done
