### ISSUE TITLE
Code/Readme inconsistency

### ISSUE THREAD

**Issue by knacky34** [dialogs/android-dialer#2]
Hello,
I've found two slight mistakes, In your README, Configuration tab, you have written EXTRA_REGION_CODE but in the code the String is set to REGION_CODE. And the default value of EXTRA_CURSOR_VISIBLE is set to false in the code and true the README file.
Goodbye :)

**Comment by bmaslakov** [comment]
Hi, thanks for noticing! I changed `REGION_CODE` to `EXTRA_REGION_CODE` and updated the readme. You can use `1.2.5` now :)
